# Generated by Django 6.0 on 2025-12-24 11:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerflight',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='trackingToken',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
