# Generated by Django 6.0 on 2025-12-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0002_passengerflight_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerflight',
            name='access_token',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='trackingToken',
            field=models.CharField(max_length=200),
        ),
    ]
