# Generated by Django 6.0 on 2025-12-24 11:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0003_remove_passengerflight_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerflight',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
