# Generated by Django 6.0 on 2025-12-24 11:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0004_passengerflight_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerflight',
            name='access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
