# Generated by Django 6.0 on 2025-12-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0005_alter_passengerflight_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='trackingToken',
        ),
    ]
