# Generated by Django 6.0 on 2025-12-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_is_protected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateassignment',
            name='boardingCloseTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gateassignment',
            name='boardingOpenTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
